#ifndef COMMON_DEF_H_
#define COMMON_DEF_H_

#define PACKAGE_LOCATION "crypto/"

#define KEYGEN_CLASS "crypto/Keys"
#define KEYGEN_GSK_VAR_NAME "gsk"
#define KEYGEN_GPK_VAR_NAME "gpk"
#define KEYGEN_GMSK_VAR_NAME "gmsk"

#define GROUP_PUBLIC_KEY_CLASS PACKAGE_LOCATION"GroupPublicKey"
#define GROUP_MASTER_SECRET_KEY_CLASS PACKAGE_LOCATION"GroupMasterSecretKey"
#define GROUP_SECRET_KEY_CLASS PACKAGE_LOCATION"GroupSecretKey"
#define ECPOINT_FP_CLASS PACKAGE_LOCATION"EcPoint_Fp"
#define ECPOINT_FP2_CLASS PACKAGE_LOCATION"EcPoint_Fp2"
#define SDH_SIGNATURE_CLASS PACKAGE_LOCATION"SdhSignature"

#define GROUP_PUBLIC_KEY_TYPE "L"GROUP_PUBLIC_KEY_CLASS";"
#define ECPOINT_FP_TYPE "L"ECPOINT_FP_CLASS";"
#define ECPOINT_FP2_TYPE "L"ECPOINT_FP2_CLASS ";"
#define GROUP_MASTER_SECRET_KEY_TYPE "L"GROUP_MASTER_SECRET_KEY_CLASS";"
#define GROUP_SECRET_KEY_TYPE "L"GROUP_SECRET_KEY_CLASS";"
#define GROUP_SECRET_KEY_ARRAY_TYPE "["GROUP_SECRET_KEY_TYPE


#endif