#spring.mvc.view.prefix=/WEB-INF/jsp/views/
#spring.mvc.view.suffix: .jsp
#logging.level.org.springframework.web=ERROR
#spring.devtools.restart.poll-interval=2s
#spring.devtools.restart.quiet-period=1s
#server.port=8082
server:
  port: 8082
  ssl:
    enabled: true
    key-store: /dc.p12
    key-store-password: my_password
    keyStoreType: PKCS12
    keyAlias: dc
    trust-store: /trusted_certs.jks
    trust-store-password: my_password
logging:
  level:
    root: ERROR
